# Generated by Django 4.2.7 on 2024-04-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_products_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description2',
            field=models.TextField(blank=True, null=True, verbose_name='Характеристика'),
        ),
    ]
