# Generated by Django 4.2.7 on 2024-04-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_products_description2'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description1',
            field=models.TextField(blank=True, null=True, verbose_name='Основной цвет'),
        ),
        migrations.AddField(
            model_name='products',
            name='description3',
            field=models.TextField(blank=True, null=True, verbose_name='Область применения'),
        ),
        migrations.AddField(
            model_name='products',
            name='description4',
            field=models.TextField(blank=True, null=True, verbose_name='Размещение'),
        ),
        migrations.AddField(
            model_name='products',
            name='description5',
            field=models.TextField(blank=True, null=True, verbose_name='Размещение'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description2',
            field=models.TextField(blank=True, null=True, verbose_name='Функции устройства'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Модель'),
        ),
    ]
