# Generated by Django 4.2.7 on 2024-05-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_categories_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='resurs',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ресурс картриджа'),
        ),
    ]
