# Generated by Django 4.2.7 on 2024-05-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_products_resurs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='interf',
        ),
        migrations.AlterField(
            model_name='products',
            name='connection',
            field=models.CharField(blank=True, null=True, verbose_name='Подключение/Интерфейс сканера'),
        ),
    ]
